apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ./api-server/docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f ./api-server/docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - env:
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  key: APP_DEBUG
                  name: mysql-env
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  key: APP_ENV
                  name: mysql-env
            - name: APP_KEY
              valueFrom:
                configMapKeyRef:
                  key: APP_KEY
                  name: mysql-env
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  key: APP_NAME
                  name: mysql-env
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  key: APP_URL
                  name: mysql-env
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: mysql-env
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: AWS_BUCKET
                  name: mysql-env
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  key: AWS_DEFAULT_REGION
                  name: mysql-env
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: mysql-env
            - name: AWS_USE_PATH_STYLE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: AWS_USE_PATH_STYLE_ENDPOINT
                  name: mysql-env
            - name: BROADCAST_DRIVER
              valueFrom:
                configMapKeyRef:
                  key: BROADCAST_DRIVER
                  name: mysql-env
            - name: CACHE_DRIVER
              valueFrom:
                configMapKeyRef:
                  key: CACHE_DRIVER
                  name: mysql-env
            - name: DB_CONNECTION
              valueFrom:
                configMapKeyRef:
                  key: DB_CONNECTION
                  name: mysql-env
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DB_DATABASE
                  name: mysql-env
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: mysql-env
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: mysql-env
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: mysql-env
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: DB_USERNAME
                  name: mysql-env
            - name: FILESYSTEM_DISK
              valueFrom:
                configMapKeyRef:
                  key: FILESYSTEM_DISK
                  name: mysql-env
            - name: LOG_CHANNEL
              valueFrom:
                configMapKeyRef:
                  key: LOG_CHANNEL
                  name: mysql-env
            - name: LOG_DEPRECATIONS_CHANNEL
              valueFrom:
                configMapKeyRef:
                  key: LOG_DEPRECATIONS_CHANNEL
                  name: mysql-env
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: LOG_LEVEL
                  name: mysql-env
            - name: MAIL_ENCRYPTION
              valueFrom:
                configMapKeyRef:
                  key: MAIL_ENCRYPTION
                  name: mysql-env
            - name: MAIL_FROM_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: MAIL_FROM_ADDRESS
                  name: mysql-env
            - name: MAIL_FROM_NAME
              valueFrom:
                configMapKeyRef:
                  key: MAIL_FROM_NAME
                  name: mysql-env
            - name: MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  key: MAIL_HOST
                  name: mysql-env
            - name: MAIL_MAILER
              valueFrom:
                configMapKeyRef:
                  key: MAIL_MAILER
                  name: mysql-env
            - name: MAIL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MAIL_PASSWORD
                  name: mysql-env
            - name: MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  key: MAIL_PORT
                  name: mysql-env
            - name: MAIL_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: MAIL_USERNAME
                  name: mysql-env
            - name: MEMCACHED_HOST
              valueFrom:
                configMapKeyRef:
                  key: MEMCACHED_HOST
                  name: mysql-env
            - name: MYSQL_DATABASE
              value: backend
            - name: MYSQL_ROOT_PASSWORD
              value: Aa648213579
            - name: PUSHER_APP_CLUSTER
              valueFrom:
                configMapKeyRef:
                  key: PUSHER_APP_CLUSTER
                  name: mysql-env
            - name: PUSHER_APP_ID
              valueFrom:
                configMapKeyRef:
                  key: PUSHER_APP_ID
                  name: mysql-env
            - name: PUSHER_APP_KEY
              valueFrom:
                configMapKeyRef:
                  key: PUSHER_APP_KEY
                  name: mysql-env
            - name: PUSHER_APP_SECRET
              valueFrom:
                configMapKeyRef:
                  key: PUSHER_APP_SECRET
                  name: mysql-env
            - name: PUSHER_HOST
              valueFrom:
                configMapKeyRef:
                  key: PUSHER_HOST
                  name: mysql-env
            - name: PUSHER_PORT
              valueFrom:
                configMapKeyRef:
                  key: PUSHER_PORT
                  name: mysql-env
            - name: PUSHER_SCHEME
              valueFrom:
                configMapKeyRef:
                  key: PUSHER_SCHEME
                  name: mysql-env
            - name: QUEUE_CONNECTION
              valueFrom:
                configMapKeyRef:
                  key: QUEUE_CONNECTION
                  name: mysql-env
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: REDIS_HOST
                  name: mysql-env
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: REDIS_PASSWORD
                  name: mysql-env
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: REDIS_PORT
                  name: mysql-env
            - name: SESSION_DRIVER
              valueFrom:
                configMapKeyRef:
                  key: SESSION_DRIVER
                  name: mysql-env
            - name: SESSION_LIFETIME
              valueFrom:
                configMapKeyRef:
                  key: SESSION_LIFETIME
                  name: mysql-env
            - name: VITE_PUSHER_APP_CLUSTER
              valueFrom:
                configMapKeyRef:
                  key: VITE_PUSHER_APP_CLUSTER
                  name: mysql-env
            - name: VITE_PUSHER_APP_KEY
              valueFrom:
                configMapKeyRef:
                  key: VITE_PUSHER_APP_KEY
                  name: mysql-env
            - name: VITE_PUSHER_HOST
              valueFrom:
                configMapKeyRef:
                  key: VITE_PUSHER_HOST
                  name: mysql-env
            - name: VITE_PUSHER_PORT
              valueFrom:
                configMapKeyRef:
                  key: VITE_PUSHER_PORT
                  name: mysql-env
            - name: VITE_PUSHER_SCHEME
              valueFrom:
                configMapKeyRef:
                  key: VITE_PUSHER_SCHEME
                  name: mysql-env
          image: mysql:8.0
          name: mysql
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-data
      restartPolicy: Always
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
