apiVersion: v1
data:
  APP_DEBUG: "true"
  APP_ENV: local
  APP_KEY: base64:JyPKDyk437HQVNlDLpCbi9ifJZlOlZwTjQVq0C8QJag=
  APP_NAME: Laravel
  APP_URL: http://localhost
  AWS_ACCESS_KEY_ID: ""
  AWS_BUCKET: ""
  AWS_DEFAULT_REGION: us-east-1
  AWS_SECRET_ACCESS_KEY: ""
  AWS_USE_PATH_STYLE_ENDPOINT: "false"
  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  DB_CONNECTION: mysql
  DB_DATABASE: backend
  DB_HOST: mysql
  DB_PASSWORD: Aa648213579
  DB_PORT: "3306"
  DB_USERNAME: root
  FILESYSTEM_DISK: local
  LOG_CHANNEL: stack
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: debug
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: hello@example.com
  MAIL_FROM_NAME: Laravel
  MAIL_HOST: mailpit
  MAIL_MAILER: smtp
  MAIL_PASSWORD: "null"
  MAIL_PORT: "1025"
  MAIL_USERNAME: "null"
  MEMCACHED_HOST: 127.0.0.1
  PUSHER_APP_CLUSTER: mt1
  PUSHER_APP_ID: ""
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""
  PUSHER_HOST: ""
  PUSHER_PORT: "443"
  PUSHER_SCHEME: https
  QUEUE_CONNECTION: sync
  REDIS_HOST: 127.0.0.1
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"
  SESSION_DRIVER: file
  SESSION_LIFETIME: "120"
  VITE_PUSHER_APP_CLUSTER: mt1
  VITE_PUSHER_APP_KEY: ""
  VITE_PUSHER_HOST: ""
  VITE_PUSHER_PORT: "443"
  VITE_PUSHER_SCHEME: https
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: mysql-mysql-env
  name: mysql-env
