apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ./api-server/docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ollama
  name: ollama
spec:
  ports:
    - name: "11343"
      port: 11343
      targetPort: 11343
  selector:
    io.kompose.service: ollama
